services:
  app:
    build: 
      context: .
    container_name: names_api
    command: uvicorn main:app --host 127.0.0.1 --port 8000 --reload
    ports:
      - "8080:80"
    volumes:
      - .:/app
