name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t random_name_gen_fastapi .

      - name: Push Docker Image to AWS ECR
        run: |
          aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin your-ecr-repository-url
          docker tag random_name_gen_fastapi:latest your-ecr-repository-url:latest
          docker push your-ecr-repository-url:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PASSWORD }}
          script: |
            docker pull your-ecr-repository-url:latest
            docker run -d -p 8000:8000 your-ecr-repository-url:latest
